name: release

on:
   workflow_dispatch:
      inputs:
         version:
            description: "The release version"
            required: true
            default: "2.2."
         branch:
            description: "The branch to release from"
            required: true
            default: 'master'

jobs:
   publish:
      runs-on: ubuntu-latest

      steps:
         -  uses: actions/checkout@v3
            with:
               fetch-depth: 0
               ref: ${{ github.event.inputs.branch }}

         -  uses: actions/setup-java@v3
            with:
               distribution: "temurin"
               java-version: "11"

         -  name: publish to sonatype
            run: ./gradlew publish

         -  name: tag release
            run: |
               git tag v${{ github.event.inputs.version }}
               git push --tags

env:
   GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=false -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
   RELEASE_VERSION: ${{ github.event.inputs.version }}
   ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }}
   ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }}
   ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
   ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
